// ===========================================
// SUPPORTED IT ROLES
// ===========================================

export const SUPPORTED_ROLES = [
    "Software Developer",
    "Web Developer",
    "Backend Engineer",
    "Frontend Engineer",
    "Full Stack Developer",
    "DevOps Engineer",
    "Site Reliability Engineer",
    "Platform Engineer",
    "Network Engineer",
    "Network Security Engineer",
    "Cyber Security Analyst",
    "SOC Analyst",
    "Security Engineer",
    "Cloud Engineer",
    "Cloud Security Engineer",
    "Cloud Architect",
    "AI / ML Engineer",
    "Data Engineer",
    "Data Scientist",
    "GRC / Compliance Analyst",
    "IT Support Specialist",
    "NOC Engineer",
    "Systems Administrator",
    "Database Administrator",
] as const;

export type SupportedRole = (typeof SUPPORTED_ROLES)[number];

// ===========================================
// EXPERIENCE LEVELS
// ===========================================

export const EXPERIENCE_LEVELS = [
    {
        value: "Fresher",
        label: "Fresher (0-1 years)",
        description: "New graduates or less than 1 year of experience",
    },
    {
        value: "1-3 Years",
        label: "Junior (1-3 years)",
        description: "Early career with some professional experience",
    },
    {
        value: "3-6 Years",
        label: "Mid-Level (3-6 years)",
        description: "Established professional with solid experience",
    },
    {
        value: "6+ Years",
        label: "Senior (6+ years)",
        description: "Senior or lead positions with extensive experience",
    },
    {
        value: "Switcher",
        label: "Career Switcher",
        description: "Transitioning from another field or role",
    },
] as const;

export type ExperienceLevel = (typeof EXPERIENCE_LEVELS)[number]["value"];

// ===========================================
// ROLE-SPECIFIC KEYWORDS
// ===========================================

export const ROLE_KEYWORDS: Record<string, string[]> = {
    "Software Developer": [
        "algorithms",
        "data structures",
        "system design",
        "testing",
        "code review",
        "git",
        "agile",
        "scrum",
        "ci/cd",
        "debugging",
        "oop",
        "design patterns",
        "rest api",
        "microservices",
        "unit testing",
    ],
    "Web Developer": [
        "html",
        "css",
        "javascript",
        "typescript",
        "react",
        "vue",
        "angular",
        "next.js",
        "responsive design",
        "accessibility",
        "wcag",
        "seo",
        "performance",
        "webpack",
        "tailwind",
    ],
    "Backend Engineer": [
        "api design",
        "database",
        "sql",
        "nosql",
        "microservices",
        "rest",
        "graphql",
        "authentication",
        "authorization",
        "caching",
        "redis",
        "message queues",
        "rabbitmq",
        "kafka",
        "scalability",
    ],
    "Frontend Engineer": [
        "react",
        "vue",
        "angular",
        "typescript",
        "javascript",
        "css",
        "sass",
        "responsive",
        "accessibility",
        "performance",
        "state management",
        "redux",
        "webpack",
        "testing",
        "jest",
    ],
    "Full Stack Developer": [
        "frontend",
        "backend",
        "database",
        "api",
        "rest",
        "full stack",
        "javascript",
        "typescript",
        "react",
        "node.js",
        "sql",
        "nosql",
        "deployment",
        "git",
        "agile",
    ],
    "DevOps Engineer": [
        "kubernetes",
        "docker",
        "terraform",
        "ansible",
        "ci/cd",
        "jenkins",
        "github actions",
        "aws",
        "azure",
        "gcp",
        "monitoring",
        "prometheus",
        "grafana",
        "linux",
        "infrastructure as code",
    ],
    "Site Reliability Engineer": [
        "sre",
        "reliability",
        "incident management",
        "on-call",
        "slo",
        "sli",
        "monitoring",
        "observability",
        "kubernetes",
        "automation",
        "toil reduction",
        "postmortem",
        "capacity planning",
        "performance",
        "chaos engineering",
    ],
    "Platform Engineer": [
        "platform",
        "kubernetes",
        "internal developer platform",
        "idp",
        "developer experience",
        "automation",
        "terraform",
        "gitops",
        "ci/cd",
        "infrastructure",
        "self-service",
        "tooling",
        "observability",
        "scalability",
    ],
    "Network Engineer": [
        "routing",
        "switching",
        "tcp/ip",
        "bgp",
        "ospf",
        "vlan",
        "firewall",
        "cisco",
        "juniper",
        "load balancing",
        "vpn",
        "dns",
        "dhcp",
        "troubleshooting",
        "network security",
    ],
    "Network Security Engineer": [
        "firewall",
        "ids",
        "ips",
        "vpn",
        "network security",
        "penetration testing",
        "vulnerability assessment",
        "siem",
        "cisco",
        "palo alto",
        "fortinet",
        "zero trust",
        "network monitoring",
        "incident response",
    ],
    "Cyber Security Analyst": [
        "threat detection",
        "incident response",
        "siem",
        "splunk",
        "vulnerability",
        "malware analysis",
        "forensics",
        "security monitoring",
        "nist",
        "iso 27001",
        "risk assessment",
        "phishing",
        "threat intelligence",
        "security awareness",
    ],
    "SOC Analyst": [
        "soc",
        "security operations",
        "siem",
        "splunk",
        "qradar",
        "incident response",
        "threat hunting",
        "log analysis",
        "alert triage",
        "playbooks",
        "soar",
        "ioc",
        "threat intelligence",
        "escalation",
    ],
    "Security Engineer": [
        "security engineering",
        "application security",
        "penetration testing",
        "vulnerability management",
        "secure coding",
        "owasp",
        "encryption",
        "authentication",
        "authorization",
        "security architecture",
        "devsecops",
        "sast",
        "dast",
    ],
    "Cloud Engineer": [
        "aws",
        "azure",
        "gcp",
        "cloud architecture",
        "serverless",
        "lambda",
        "ec2",
        "s3",
        "vpc",
        "iam",
        "cloudformation",
        "cost optimization",
        "migration",
        "hybrid cloud",
        "multi-cloud",
    ],
    "Cloud Security Engineer": [
        "cloud security",
        "aws security",
        "azure security",
        "iam",
        "identity management",
        "encryption",
        "compliance",
        "cspm",
        "cwpp",
        "container security",
        "network security",
        "security groups",
        "waf",
        "ddos",
    ],
    "Cloud Architect": [
        "cloud architecture",
        "aws",
        "azure",
        "gcp",
        "solution architecture",
        "well-architected",
        "scalability",
        "high availability",
        "disaster recovery",
        "cost optimization",
        "migration",
        "hybrid cloud",
        "multi-cloud",
        "enterprise architecture",
    ],
    "AI / ML Engineer": [
        "machine learning",
        "deep learning",
        "neural networks",
        "tensorflow",
        "pytorch",
        "python",
        "model training",
        "mlops",
        "feature engineering",
        "model deployment",
        "nlp",
        "computer vision",
        "data pipeline",
        "a/b testing",
        "experimentation",
    ],
    "Data Engineer": [
        "data pipeline",
        "etl",
        "data warehouse",
        "spark",
        "airflow",
        "sql",
        "python",
        "data modeling",
        "data lake",
        "snowflake",
        "databricks",
        "kafka",
        "streaming",
        "batch processing",
        "data quality",
    ],
    "Data Scientist": [
        "machine learning",
        "statistics",
        "python",
        "r",
        "data analysis",
        "visualization",
        "pandas",
        "scikit-learn",
        "hypothesis testing",
        "regression",
        "classification",
        "clustering",
        "feature engineering",
        "jupyter",
    ],
    "GRC / Compliance Analyst": [
        "grc",
        "governance",
        "risk management",
        "compliance",
        "audit",
        "iso 27001",
        "soc 2",
        "gdpr",
        "hipaa",
        "pci-dss",
        "nist",
        "controls",
        "policy",
        "risk assessment",
        "third party risk",
    ],
    "IT Support Specialist": [
        "help desk",
        "troubleshooting",
        "windows",
        "macos",
        "active directory",
        "office 365",
        "hardware",
        "software installation",
        "ticketing system",
        "customer service",
        "remote support",
        "networking basics",
    ],
    "NOC Engineer": [
        "network operations",
        "monitoring",
        "incident management",
        "24x7",
        "nagios",
        "zabbix",
        "solarwinds",
        "ticketing",
        "escalation",
        "troubleshooting",
        "documentation",
        "runbooks",
        "on-call",
    ],
    "Systems Administrator": [
        "linux",
        "windows server",
        "active directory",
        "vmware",
        "backup",
        "disaster recovery",
        "automation",
        "scripting",
        "powershell",
        "bash",
        "patch management",
        "security hardening",
        "monitoring",
    ],
    "Database Administrator": [
        "database administration",
        "mysql",
        "postgresql",
        "oracle",
        "sql server",
        "mongodb",
        "backup and recovery",
        "performance tuning",
        "query optimization",
        "replication",
        "high availability",
        "security",
    ],
};

// ===========================================
// ROLE EXPECTATIONS (For AI Context)
// ===========================================

export const ROLE_EXPECTATIONS: Record<string, string[]> = {
    "Software Developer": [
        "Strong DSA fundamentals demonstrated through projects or competitive programming",
        "System design knowledge for scale (even basic)",
        "Proficiency in at least one programming language with depth",
        "Testing experience (unit, integration)",
        "Version control and collaboration workflows",
    ],
    "Web Developer": [
        "Modern frontend framework expertise (React/Vue/Angular)",
        "CSS mastery and responsive design",
        "Accessibility (WCAG) awareness",
        "Performance optimization knowledge",
        "Basic SEO understanding",
    ],
    "DevOps Engineer": [
        "Container orchestration (Kubernetes preferred)",
        "Infrastructure as Code (Terraform/Pulumi)",
        "CI/CD pipeline design and implementation",
        "Cloud platform expertise (AWS/Azure/GCP)",
        "Monitoring and observability stack experience",
    ],
    "Network Engineer": [
        "Routing protocols (BGP, OSPF, EIGRP)",
        "Switching concepts and VLANs",
        "Firewall configuration and management",
        "Network troubleshooting methodology",
        "Vendor certification or equivalent experience",
    ],
    "Cyber Security Analyst": [
        "Threat detection and analysis skills",
        "SIEM platform experience (Splunk, QRadar, etc.)",
        "Incident response procedures",
        "Security framework knowledge (NIST, ISO 27001)",
        "Log analysis and forensics basics",
    ],
    "Cloud Security Engineer": [
        "Cloud-native security controls (IAM, Security Groups, WAF)",
        "Compliance frameworks (SOC 2, ISO 27001, etc.)",
        "Container and workload security",
        "Threat modeling for cloud architectures",
        "Security automation and policy as code",
    ],
    "AI / ML Engineer": [
        "Strong mathematical foundations (linear algebra, statistics, calculus) - can be demonstrated via professional experience OR academic coursework",
        "Model training and evaluation experience (projects, internships, or Kaggle/Amazon ML challenges)",
        "MLOps and model deployment knowledge (Senior: productionized; Junior: Streamlit/Flask/Local)",
        "Framework expertise (TensorFlow/PyTorch/Scikit-Learn)",
        "Real-world ML project experience with measurable outcomes or ranking in technical competitions",
    ],
    "Data Engineer": [
        "ETL/ELT pipeline development",
        "Data warehouse design",
        "Big data technologies (Spark, etc.)",
        "SQL and data modeling",
        "Workflow orchestration (Airflow, etc.)",
    ],
};

// ===========================================
// ACTION VERBS
// ===========================================

export const ACTION_VERBS = [
    "achieved",
    "administered",
    "analyzed",
    "architected",
    "automated",
    "built",
    "collaborated",
    "configured",
    "consolidated",
    "created",
    "debugged",
    "decreased",
    "delivered",
    "deployed",
    "designed",
    "developed",
    "devised",
    "diagnosed",
    "documented",
    "drove",
    "eliminated",
    "enabled",
    "engineered",
    "enhanced",
    "established",
    "evaluated",
    "executed",
    "expanded",
    "expedited",
    "facilitated",
    "formulated",
    "generated",
    "guided",
    "identified",
    "implemented",
    "improved",
    "increased",
    "initiated",
    "innovated",
    "installed",
    "integrated",
    "introduced",
    "launched",
    "led",
    "leveraged",
    "maintained",
    "managed",
    "maximized",
    "migrated",
    "minimized",
    "modernized",
    "monitored",
    "negotiated",
    "optimized",
    "orchestrated",
    "organized",
    "oversaw",
    "performed",
    "pioneered",
    "planned",
    "prepared",
    "presented",
    "prioritized",
    "produced",
    "programmed",
    "proposed",
    "provided",
    "published",
    "redesigned",
    "reduced",
    "refactored",
    "refined",
    "remediated",
    "replaced",
    "resolved",
    "restructured",
    "reviewed",
    "revised",
    "scaled",
    "secured",
    "simplified",
    "solved",
    "spearheaded",
    "standardized",
    "streamlined",
    "strengthened",
    "supervised",
    "supported",
    "surpassed",
    "tested",
    "trained",
    "transformed",
    "troubleshot",
    "unified",
    "upgraded",
    "utilized",
    "validated",
    "verified",
];

// ===========================================
// DISALLOWED PHRASES (For AI Tone)
// ===========================================

export const DISALLOWED_PHRASES = [
    "great potential",
    "keep learning",
    "you are on the right path",
    "you can improve",
    "good start",
    "promising",
    "well done",
    "excellent effort",
    "nice work",
    "keep it up",
    "don't give up",
    "believe in yourself",
    "you've got this",
    "stay positive",
    "great job",
];
